docmanag/urls.py
from django.urls import path, include

from . import views

app_name = 'docmanag'
urlpatterns = [
    #path('', views.index, name='index'),
    #sondage/5/
    #path('detail/<int:question_id>/', views.detail, name='detail'),
     #sondage/5/results/
    #path('<int:question_id>/results/', views.resultats, name='resultats'),
     #sondage/5/vote/
    #path('<int:question_id>/vote/', views.vote, name='vote'),
    #path('', views.IndexView.as_view(), name='index'),
    #path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    #path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    #path('<int:question_id>/vote/', views.vote, name='vote'),
    #path('register/', views.Register, name='register'),
    ##path('login/', views.Login, name='login'),
    #path('storeuser/',  views.Storeuser, name='storeuser'),/docmanag/
    
    path('home/', views.Home, name='home'),
    path('details/', views.Details, name='details'),
    path('account/', views.Account, name='account'),
    path('accountcoord/', views.Accountcoord, name='accountcoord'),
    path('storeordremission/',  views.Storeordremission, name='storeordremission'),
    path('editordremission/',  views.Editordremission, name='editordremission'),
    path('boitereception/',  views.Boitereception, name='boitereception'),
    path('boitereceptioncn/',  views.Boitereceptioncoord, name='boitereceptioncn'),
    
    path('historique/',  views.Historique, name='historique'),
    path('historiquecoord/',  views.Historiquecoord, name='historiquecoord'),
    path('logine/', views.login_user, name='logine'),
    path('addsignat/', views.signature, name='signature'),
    path('signer/<int:om_id>/', views.signer, name='signer'),
    path('render/pdf/', views.Pdf.as_view()),   
    path('chatcn/<int:env_id>/<int:sender>/<int:receiver>/', views.Messageviewbiscoord, name='chatcn'),
    path('chat/<int:env_id>/<int:sender>/<int:receiver>/', views.Messageviewbis, name='chat'),
    path('envoiyer/', views.Envoiyer, name='envoi'),
    path('api/messages/<int:env_id>/<int:sender>/<int:receiver>/', views.message_list, name='message-detail'),
    path('api/messages/<int:env_id>/<int:sender>/<int:receiver>/<str:message>/', views.message_list, name='message-list'),

    path('send/<int:env_id>/', views.send, name='send'),
    path('visualiser/', views.visualiser, name='visualiser'),
    path('deleteom/', views.deleteom, name='deleteom'),

    path('register/', views.Register, name='register'),
    path('storeuser/',  views.Storeuser, name='storeuser'),
    path('accounts/', include('django.contrib.auth.urls')),
]

docmansaas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls
from django.conf.urls import url

urlpatterns = [
    path('docmanag/', include('docmanag.urls')),
    path('admin/', admin.site.urls),
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

docmanag/models.py
from django.core import validators
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db.models.deletion import CASCADE
from django.db import models
from django.utils import timezone
import uuid
from django.utils.translation import gettext_lazy as _
from docmanag.validate import validator_image


from docmanag.validator import  validator


from .managers import CustomUserManager
from django.core.validators import FileExtensionValidator
from django.core.exceptions import ValidationError
def logofile(instance, filename):
    return '/'.join(['logo', filename])
def pdffile(instance, filename):
    return '/'.join(['pdf',filename])


class User(AbstractBaseUser, PermissionsMixin):
    ROLE1 = 1
    ROLE2 = 2
    ROLE3 =3
    ROLE4 =4
    ROLE5 =5
    ROLE6=6
    ROLE7=7
    ROLE8=8
    ROLE9=9
    ADMIN=10

      
    ROLE_CHOICES = (
          (ROLE1, 'role1'),
          (ROLE2, 'role2'),
          (ROLE3, 'role3'),
          (ROLE4, 'role4'),
          (ROLE5, 'role5'),
          (ROLE6, 'role6'),
          (ROLE7, 'role7'),
          (ROLE8, 'role8'),
          (ROLE9, 'role9'),
          (ADMIN, 'admin'),
          
      )
    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICES, blank=True, null=True)
    email = models.EmailField(_('email address'), unique=True)
    username = models.CharField(max_length=100, null=True, blank=True)
    firstname=models.CharField(max_length=255, null=True, blank=True)
    lastname=models.CharField(max_length=255, null=True, blank=True)
    photoprofil=models.ImageField(upload_to='userfile/covers/', null=True, blank=True, validators=[validator_image])
    signature=models.ImageField(upload_to='userfile/covers/', null=True, blank=True, validators=[validator_image])
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email


class Userfile(models.Model):
   user=models.ForeignKey(User, on_delete=models.CASCADE)
   title = models.CharField(max_length=100)
   author = models.CharField(max_length=100)
   pdf = models.FileField(upload_to='userfile/pdfs/')
   cover = models.ImageField(upload_to='userfile/covers/', null=True, blank=True)

   def __str__(self):
       return self.title
   
   def delete(self, *args, **kwargs):
      self.pdf.delete()
      self.cover.delete()
      super().delete(*args, **kwargs)



class Ordremission(models.Model):  
   user=models.ForeignKey(User, on_delete=models.CASCADE)
   objetmission=models.CharField(max_length=255, null=True, blank=True)
   datedepart= models.DateField(null=True, blank=True)
   dateretour= models.DateField(null=True, blank=True)
   adressemission=models.CharField(max_length=255, null=True, blank=True)
   transport=models.CharField(max_length=255, null=True, blank=True)
   adressehebergement=models.CharField(max_length=255, null=True, blank=True)
   adresseemploye=models.CharField(max_length=255, null=True, blank=True)
   prenom=models.CharField(max_length=255, null=True, blank=True)
   nom=models.CharField(max_length=255, null=True, blank=True)
   motif=models.CharField(max_length=255, null=True, blank=True)
   nomchauffeur=models.CharField(max_length=255, null=True, blank=True)
   kilomdepart=models.IntegerField(default=0)
   kilomarrivee=models.IntegerField(default=0)
   datecreat=models.DateField(default=timezone.now)
   signatureemployeur=models.CharField(max_length=255, null=True, blank=True)
   createdat =models.DateTimeField(auto_now_add=True)
   fichier_an_one = models.FileField(upload_to=pdffile, null=True, blank=True, validators=[validator])
   fichier_an_two = models.FileField(upload_to=pdffile, null=True, blank=True, validators=[validator])
   fichier_genere = models.FileField(upload_to=pdffile, null=True, blank=True, validators=[validator])
   is_evoiyer= models.BooleanField(default=False)
   is_signer = models.BooleanField(default=False)
   
   class Meta:
         ordering = ('createdat',)
   

class Envoi(models.Model):
   ordremission=models.ForeignKey(Ordremission, on_delete=models.CASCADE)
   initiateur = models.ForeignKey(User, on_delete=models.CASCADE, related_name='initiateur')
   recepteur = models.ForeignKey(User, on_delete=models.CASCADE, related_name='recepteur')
   createdatenv =models.DateTimeField(auto_now_add=True)
   is_send = models.BooleanField(default=False)
   is_signe = models.BooleanField(default=False)
   

   class Meta:
         ordering = ('createdatenv',)

class Message(models.Model):
   envoi=models.ForeignKey(Envoi, on_delete=models.CASCADE)
   sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
   receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver')
   message = models.CharField(max_length=1200, null=True, blank=True)
   timestamp = models.DateTimeField(auto_now_add=True)
   is_read = models.BooleanField(default=False)

   def __str__(self):
        return str(self.message)

   class Meta:
     ordering = ('timestamp',)

docmanag/forms.py
from django.forms import ModelForm
from django import forms

from .models import Ordremission
from django.core.exceptions import ValidationError



class OrdremissionForm(ModelForm):
    
   # meta data for displaying a form
   class Meta:
      # model
      model = Ordremission

      # displaying fields
      fields = ['objetmission', 'datedepart', 'dateretour', 'adressemission', 'transport', 'adressehebergement', 'adresseemploye', 'fichier_an_one', 'fichier_an_two'] 
      labels = {'objetmission':'Objet de la mission','datedepart':'Date de départ', 'dateretour':'Date de retour', 'adressemission':'Adresse de la mission','transport': 'Moyens de transport','adressehebergement':'Adresse Hébergement','adresseemploye':'Adresse du demandeur', 'fichier_an_one':'Fichier Annexe 1', 'fichier_an_two':'Fichier Annexe 2'}
      widgets = {
        'datedepart': forms.DateInput(format=('%m/%d/%Y'), attrs={'class':'form-control', 'placeholder':'Select a date', 'type':'date'}),
        'dateretour': forms.DateInput(format=('%m/%d/%Y'), attrs={'class':'form-control', 'placeholder':'Select a date', 'type':'date'}),
        #'fichier_an_one':forms.FileInput(attrs={'accept': 'application/pdf', 'required':'required'})
      }  

 

docmanag/templates/docmanag/login.html
<!DOCTYPE html>
<html lang="fr">

<head>
    <title>DEDRAS OM</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <!-- Favicon icon -->
    {% load static %}
    <link rel="icon" href="{% static 'docmanag/assets/images/favicon.ico'%}" type="image/x-icon">
    <!-- Google font-->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500" rel="stylesheet">
    <!-- waves.css -->
    <link rel="stylesheet" href="{% static 'docmanag/assets/pages/waves/css/waves.min.css'%}" type="text/css" media="all">
    <!-- Required Fremwork -->
    <link rel="stylesheet" type="text/css" href="{% static 'docmanag/assets/css/bootstrap/css/bootstrap.min.css'%}">
    <!-- waves.css -->
    <link rel="stylesheet" href=" {% static 'docmanag/assets/pages/waves/css/waves.min.css'%}" type="text/css" media="all">
    <!-- themify icon -->
    <link rel="stylesheet" type="text/css" href="{% static 'docmanag/assets/icon/themify-icons/themify-icons.css'%}">
    <!-- Font Awesome -->
    <link rel="stylesheet" type="text/css" href="{% static 'docmanag/assets/icon/font-awesome/css/font-awesome.min.css'%}">
    <!-- scrollbar.css -->
    <link rel="stylesheet" type="text/css" href="{% static 'docmanag/assets/css/jquery.mCustomScrollbar.css'%}">
    <!-- am chart export.css -->
    <link rel="stylesheet" href="https://www.amcharts.com/lib/3/plugins/export/export.css" type="text/css" media="all" />
    <!-- Style.css -->
    <link rel="stylesheet" type="text/css" href=" {% static 'docmanag/assets/css/style.css'%}">
    <!--

             AJOUT CRUD MODAL

    -->




    <link rel="stylesheet" type="text/css" href=" {% static 'docmanag/assets/css/style.css'%}">
    <!--

             AJOUT CRUD MODAL

    -->
    <!-- Appel de la Feuille de style minifiée De La librairie Bootstrap -->
    <!-- Appel de la Feuille de style minifiée De l'extension Datepicker -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">


    <script src="https://kit.fontawesome.com/5846046699.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
</head>

<body themebg-pattern="theme1">
    <!-- Pre-loader start -->
    <div class="theme-loader">
        <div class="loader-track">
            <div class="preloader-wrapper">
                <div class="spinner-layer spinner-blue">
                    <div class="circle-clipper left">
                        <div class="circle"></div>
                    </div>
                    <div class="gap-patch">
                        <div class="circle"></div>
                    </div>
                    <div class="circle-clipper right">
                        <div class="circle"></div>
                    </div>
                </div>
                <div class="spinner-layer spinner-red">
                    <div class="circle-clipper left">
                        <div class="circle"></div>
                    </div>
                    <div class="gap-patch">
                        <div class="circle"></div>
                    </div>
                    <div class="circle-clipper right">
                        <div class="circle"></div>
                    </div>
                </div>

                <div class="spinner-layer spinner-yellow">
                    <div class="circle-clipper left">
                        <div class="circle"></div>
                    </div>
                    <div class="gap-patch">
                        <div class="circle"></div>
                    </div>
                    <div class="circle-clipper right">
                        <div class="circle"></div>
                    </div>
                </div>

                <div class="spinner-layer spinner-green">
                    <div class="circle-clipper left">
                        <div class="circle"></div>
                    </div>
                    <div class="gap-patch">
                        <div class="circle"></div>
                    </div>
                    <div class="circle-clipper right">
                        <div class="circle"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Pre-loader end -->

    <section class="login-block">
        <!-- Container-fluid starts -->
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <!-- Authentication card start -->
                    {% if form.errors %}
                    <p>Your username and password didn't match. Please try again.</p>
                    {% endif %} {% if next %} {% if user.is_authenticated %}
                    <p>Your account doesn't have access to this page. To proceed, please login with an account that has access.</p>
                    {% else %}
                    <p>Please login to see this page.</p>
                    {% endif %} {% endif %}

                    <form class="md-float-material form-material" action="{%url 'docmanag:logine'%}" method="post">
                        {% csrf_token %} {% if next %}
                        <input type="hidden" name="next" value="{{ next }}" /> {% endif %}
                        <div class="text-center">
                            <img src="{% static 'docmanag/assets/images/favicon.png'%}" alt="logo.png">
                        </div>
                        <div class="auth-box card">
                            <div class="card-block">
                                <div class="row m-b-20">
                                    <div class="col-md-12">
                                        <h3 class="text-center">Connexion</h3>
                                    </div>
                                </div>
                                <div class="form-group form-primary">
                                    <input type="email" id="username" name="username" class="form-control" required="">
                                    <span class="form-bar"></span>
                                    <label class="float-label">Addresse e-mail </label>
                                </div>
                                <div class="form-group form-primary">
                                    <input type="password" name="password" class="form-control" required="">
                                    <span class="form-bar"></span>
                                    <label class="float-label">Mot de passe</label>
                                </div>
                                <div class="row m-t-25 text-left">
                                    <div class="col-12">
                                        <!--
                                        <div class="checkbox-fade fade-in-primary d-">
                                            <label>
                                                    <input type="checkbox" value="">
                                                    <span class="cr"><i class="cr-icon icofont icofont-ui-check txt-primary"></i></span>
                                                    <span class="text-inverse">Se souvenir de moi</span>
                                                </label>
                                        </div>-->
                                        <div class="forgot-phone text-right f-right">
                                            <a href="{% url 'docmanag:password_reset'%}" class="text-right f-w-600"> Mot de passe oublié?</a>
                                        </div>
                                        <div class="forgot-phone text-left f-left">
                                            <a href="{%url 'docmanag:register'%}">Inscriver vous ici</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="row m-t-30">
                                    <div class="col-md-12">
                                        <button type="submit" class="btn btn-primary btn-md btn-block waves-effect waves-light text-center m-b-20">Connexion</button>
                                    </div>
                                </div>
                                <hr/>
                                <div class="row">

                                </div>
                            </div>
                        </div>
                    </form>
                    <!-- end of form -->
                </div>
                <!-- end of col-sm-12 -->
            </div>
            <!-- end of row -->
        </div>
        <!-- end of container-fluid -->
    </section>
    <!-- Warning Section Starts -->
    <!-- Older IE warning message -->
    <!--[if lt IE 10]>
<div class="ie-warning">
    <h1>Warning!!</h1>
    <p>You are using an outdated version of Internet Explorer, please upgrade <br/>to any of the following web browsers to access this website.</p>
    <div class="iew-container">
        <ul class="iew-download">
            <li>
                <a href="http://www.google.com/chrome/">
                    <img src="assets/images/browser/chrome.png" alt="Chrome">
                    <div>Chrome</div>
                </a>
            </li>
            <li>
                <a href="https://www.mozilla.org/en-US/firefox/new/">
                    <img src="assets/images/browser/firefox.png" alt="Firefox">
                    <div>Firefox</div>
                </a>
            </li>
            <li>
                <a href="http://www.opera.com">
                    <img src="assets/images/browser/opera.png" alt="Opera">
                    <div>Opera</div>
                </a>
            </li>
            <li>
                <a href="https://www.apple.com/safari/">
                    <img src="assets/images/browser/safari.png" alt="Safari">
                    <div>Safari</div>
                </a>
            </li>
            <li>
                <a href="http://windows.microsoft.com/en-us/internet-explorer/download-ie">
                    <img src="assets/images/browser/ie.png" alt="">
                    <div>IE (9 & above)</div>
                </a>
            </li>
        </ul>
    </div>
    <p>Sorry for the inconvenience!</p>
</div>
<![endif]-->
    <!-- Warning Section Ends -->
    <!-- Required Jquery -->
    <!-- Required Jquery -->
    <script type="text/javascript " src="{% static 'docmanag/assets/js/jquery/jquery.min.js'%} "></script>
    <script type="text/javascript " src="{% static 'docmanag/assets/js/jquery-ui/jquery-ui.min.js'%} "></script>
    <script type="text/javascript " src="{% static 'docmanag/assets/js/popper.js/popper.min.js'%} "></script>
    <script type="text/javascript " src="{% static 'docmanag/assets/js/bootstrap/js/bootstrap.min.js'%} "></script>
    <script type="text/javascript " src="{% static 'docmanag/assets/pages/widget/excanvas.js'%} "></script>
    <!-- waves js -->
    <script src="{% static 'docmanag/assets/pages/waves/js/waves.min.js'%} "></script>
    <!-- jquery slimscroll js -->
    <script type="text/javascript " src="{% static 'docmanag/assets/js/jquery-slimscroll/jquery.slimscroll.js'%} "></script>
    <!-- modernizr js -->
    <script type="text/javascript " src="{% static 'docmanag/assets/js/modernizr/modernizr.js'%} "></script>
    <!-- slimscroll js -->
    <script type="text/javascript " src="{% static 'docmanag/assets/js/SmoothScroll.js'%} "></script>
    <script src="{% static 'docmanag/assets/js/jquery.mCustomScrollbar.concat.min.js'%} "></script>
    <!-- Chart js -->
    <script type="text/javascript " src="{% static 'docmanag/assets/js/chart.js/Chart.js'%} "></script>
    <!-- amchart js -->
    <script src="https://www.amcharts.com/lib/3/amcharts.js "></script>
    <script src="{% static 'docmanag/assets/pages/widget/amchart/gauge.js'%} "></script>
    <script src="{% static 'docmanag/assets/pages/widget/amchart/serial.js'%} "></script>
    <script src="{% static 'docmanag/assets/pages/widget/amchart/light.js'%} "></script>
    <script src="{% static 'docmanag/assets/pages/widget/amchart/pie.min.js'%} "></script>
    <script src="https://www.amcharts.com/lib/3/plugins/export/export.min.js "></script>
    <!-- menu js -->
    <script src="{% static 'docmanag/assets/js/pcoded.min.js'%} "></script>
    <script src="{% static 'docmanag/assets/js/vertical-layout.min.js'%} "></script>
    <!-- custom js -->
    <script type="text/javascript " src="{% static 'docmanag/assets/pages/dashboard/custom-dashboard.js'%} "></script>
    <script type="text/javascript " src="{% static 'docmanag/assets/js/script.js '%} "></script>
</body>

</html>

docmanag/templates/docmanag/messagescoord.html
{% extends 'docmanag/boitereceptioncoord.html' %} {% block hide %}{% endblock %} {% block messages %}

<div class="card-header msg_head">
    <div class="d-flex bd-highlight">
        <div class="img_cont">
        </div>
        <div class="user_info">
            <span></span>
            <p></p>
        </div>
        <div class="video_cam">
            <span><!--<i class="fas fa-video"></i>--></span>
            <span><!--<i class="fas fa-phone"></i>--></span>
        </div>
    </div>
    <!--<span id="action_menu_btn"><i class="fas fa-ellipsis-v"></i></span>
    <div class="action_menu">
        <ul>
            <li><i class="fas fa-user-circle"></i> View profile</li>
            <li><i class="fas fa-users"></i> Add to close friends</li>
            <li><i class="fas fa-plus"></i> Add to group</li>
            <li><i class="fas fa-ban"></i> Block</li>
        </ul>
    </div>-->
</div>
<div class="card-body msg_card_body">
    {% for message in messages %} {% if message.sender == request.user %}
    <div class="d-flex justify-content-end mb-4">
        <div class="msg_cotainer_send">{{ message }} <span class="msg_time_send">Vous, 8:55 AM, Today</span></div>
        <div class="img_cont_msg"></div>

    </div>
    {% else %}
    <div class="d-flex justify-content-start mb-4">
        <div class="img_cont_msg">

        </div>
        <div class="msg_cotainer">
            {{ message }}
            <span class="msg_time">{{ message.sender.username }}, Le 8:40 AM, Today</span>
        </div>
    </div>
    {% endif %} {% endfor %}


</div>

<div class="card-footer">

    <!--
    <div class="input-group">
        <div class="input-group-append">
            <span class="input-group-text attach_btn"><i class="fas fa-paperclip"></i></span>
        </div>
        <textarea name="" class="form-control type_msg" placeholder="Type your message..."></textarea>
        <div class="input-group-append">
            <span class="input-group-text send_btn"><i class="fas fa-location-arrow"></i></span>
        </div>
    </div>-->
</div>


<script>
    $(function() {
        $('#user{{receiver.id}}').addClass('active');
        //Call receive function each 1 seconds to check for new messages in the database
        setInterval(receive, 20000)
    })
</script>
{% endblock %} {%block sender %}
<diV class="col-md-12">
    <form id="chat-box" class="form-group" method="post">
        {% csrf_token %}
        <div class="row">

            <input type="hidden" name="env_id" id="end_id" value="{{env_id}}" />
            <input type="hidden" name="sender" id="sender" value="{{sender}}" />
            <input type="hidden" name="receiver" id="receiver" value="{{receiver}}" />


        </div>
        <div class="chat-input-holder">

            <textarea id="id_message" class="chat-input" name="message" type="text" placeholder="Type your message.."></textarea>
            <button class="input-group-text send_btn" style="background-color: rgb(218, 12, 12); width: 105px;"><i class="fas fa-location-arrow"></i></button>
        </div>






</div>


</form>
</diV>{% endblock %}

docmanag/templates/docmanag/omsigne.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title></title>
    {% load static %}

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <style type="text/css">

    </style>

</head>

<body>
    <table>
        <th>


        </th>
        <tbody>
            <td>
                <div class="">
                    <!--This popup modal will be opened by the ajax call - Important-->
                    <div class="container">
                        <p style="text-align:center;font-size: 25px; color: black; padding-left: 0;"><span id="">DEDRAS-ONG ORDRE DE MISSION
                            
                      </span></p>
                    </div>

                    <p style="font-size: 22px; color: black; padding-left: 0; text-align:justify; padding-top: 15px;">
                        No ____________/21/DEDRAS/CN/AC



                    </p>
                    <h1 id="" style="font-size: 25px; color: black;">Objet:<span id="objetmissio" style="font-size: 25px; color: black;">{{objetmission}}</span></h1>

                    <p style="font-size: 22px; color: black; padding-left: 0; text-align:justify; padding-top: 15px;">
                        Le <span style="font-weight: bold;">Coordonateur National</span> de l'Organisation pour le Développement, le Renforcement et l'Auto-promotion des Structures Communautaires <span style="font-weight: bold;">(DEDRAS-ONG), ordonne à:</span>




                    </p>
                    <p style="font-size: 22px; color: black; padding-left: 0; text-align:justify; padding-top: 15px;">
                        Au(x) Nommé(es) : <span id="nommyom" style="font-weight: bold;">{{nom}}</span></br>
                        Fonction : <span id="prenommyom" style="font-weight: bold;">{{prenom}}</span></br>
                        De se rendre à: <span id="adressemissio" style="font-weight: bold;">{{adressemission}}</span></br>
                        Lieu de provenance: <span id="adresseemploy" style="font-weight: bold;">{{adresseemploye}}</span></br>


                        Pour (Objet complet) : <span id="objetmissiobis" style="font-weight: bold;">{{objetmission}}</span></br>
                        Date de départ : <span id="datedepar" style="font-weight: bold;">{{datedepart}}</span></br>
                        Date de retour : <span id="dateretou" style="font-weight: bold;">{{dateretour}}</span></br>

                        Date effective de retour : <span id="" style="font-weight: bold;"></span></br>


                        Numéro du Véhicule : <span id="transporta" style="font-weight: bold;">{{transport}}</span></br>
                        Nom du Chauffeur : <span id="nomchaufe" style="font-weight: bold;"></span>{{nomchaufe}}</br>
                        Compteur (Km) au départ : <span id="kilomdepe" style="font-weight: bold;">{{kilomdep}}</span></br>
                        Compteur (Km) au retour : <span id="kilomarre" style="font-weight: bold;">{{kilomarr}}</span></br>





                    </p>
                    <p style="font-size: 22px; color: black; padding-left: 0; text-align:justify; padding-top: 15px;">
                        Nous prions les autorités administratives et routières de leur faciliter le passage dans l'accomplissement de la mission.




                    </p>
                    <div class="container">
                        <p style="font-size: 22px; color: black; padding-left: 0; text-align:justify; padding-top: 15px;">
                            </br>
                            </br>
                            </br>Fait à Parakou, le <span id="createda" style="font-weight: bold;">{{datecreat|date:'d-m-Y'}}</span>,</br>
                            </br>Le Coordonnateur National <span id="createda" style="font-weight: bold;"></span>,</br>
                            </br>
                            </br>
                            <span id="signatureemployeu"></span>



                        </p>
                    </div>
                    <div class="container">
                        <p style="text-align: center;"><span id="signatureemployeu">
                            <img src="{{user.signature.url}}" class="" alt="User-Profile-Image" style="height:60px; width:150px;">
                      </span></p>
                    </div>
                    <div class="container">
                        <p style="text-align:center;font-size: 22px; color: black; padding-left: 0;"><span id="">KPETERE Jean
                            
                      </span></p>
                    </div>
                    <p style="font-size: 22px; color: black; padding-left: 0; text-align:justify; padding-top: 15px;">
                        NB: Toute ratures ou surcharges annulent la validité de ce document



                    </p>
                    <p style="font-size: 22px; color: black; padding-left: 0; text-align:justify; padding-top: 15px;">
                        <span style="font-weight: bold;">Dedras ONG</span>
                        <span>BP 215 Parakou, République du Bénin</span></br>
                        <span>Tél: +229 9585 1708/ +229 9737 2972| E-mail: info@dedras.org| www.dedras.org</span></br>
                        <span>IFU No 6201101673406 | CNSS No 23866</span></br>





                    </p>




                    <!--<div style="padding-top: 1.5rem;">
                            <button type="button" class="btn btn-outline-info waves-effect ml-auto" data-dismiss="modal">Valider</button>
                    </div>-->


                </div>




            </td>



        </tbody>






    </table>


</body>

</html>